[debug] [2018-04-03T03:23:12.882Z] ----------------------------------------------------------------------
[debug] [2018-04-03T03:23:12.882Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\chautnnguyen\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase login --interactive
[debug] [2018-04-03T03:23:12.882Z] CLI Version:   3.17.7
[debug] [2018-04-03T03:23:12.882Z] Platform:      win32
[debug] [2018-04-03T03:23:12.882Z] Node Version:  v8.10.0
[debug] [2018-04-03T03:23:12.882Z] Time:          Tue Apr 03 2018 10:23:12 GMT+0700 (SE Asia Standard Time)
[debug] [2018-04-03T03:23:12.882Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=544425505&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2018-04-03T03:23:18.563Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/AACA0vU4b_u6fEr3ucYwgVHuJM96rMuQXuptS2EQ6fvQtL2hYH8E6Dv9QuwtNMxmuUhktCdvT1xfe7fuJrr05Ms',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Tue Apr 03 2018 10:23:18 GMT+0700 (SE Asia Standard Time)
[debug] [2018-04-03T03:23:18.751Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\chautnnguyen\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:17)
    at Request._callback (C:\Users\chautnnguyen\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:34:23)
    at self.callback (C:\Users\chautnnguyen\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\chautnnguyen\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
[debug] [2018-04-03T03:23:46.824Z] ----------------------------------------------------------------------
[debug] [2018-04-03T03:23:46.826Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\chautnnguyen\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase login --interactive
[debug] [2018-04-03T03:23:46.826Z] CLI Version:   3.17.7
[debug] [2018-04-03T03:23:46.826Z] Platform:      win32
[debug] [2018-04-03T03:23:46.826Z] Node Version:  v8.10.0
[debug] [2018-04-03T03:23:46.826Z] Time:          Tue Apr 03 2018 10:23:46 GMT+0700 (SE Asia Standard Time)
[debug] [2018-04-03T03:23:46.826Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=892483123&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2018-04-03T03:23:55.908Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/AABk40sNr2Ucd5IMTIDL1QrJNulv3MMh2v8we192xhVDJ7rEOIvjwwG0aK7aA3_DsDup0HNFCzEm20TXoqff-ps',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Tue Apr 03 2018 10:23:55 GMT+0700 (SE Asia Standard Time)
[debug] [2018-04-03T03:23:56.094Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\chautnnguyen\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:17)
    at Request._callback (C:\Users\chautnnguyen\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:34:23)
    at self.callback (C:\Users\chautnnguyen\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\chautnnguyen\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
